import Head from 'next/dist/shared/lib/head';
import Script from 'next/script';

function Index() {
  return (
    <div>
      <Head>
        <title>Hunter Coder </title>
        <meta name="description" content="Generated by me" />
        <link rel="icon" href="/favicon.ico" />
        <Script src=" " strategy="lazyOnload"></Script>
      </Head>
    </div>
  );
}

export default Index;
